// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8W5YqlSjmOYjBEe7axxDYcv0iryitUk4',
    appId: '1:510416218437:web:596e857aa3603a15e5762c',
    messagingSenderId: '510416218437',
    projectId: 'gymapp-eff8d',
    authDomain: 'gymapp-eff8d.firebaseapp.com',
    storageBucket: 'gymapp-eff8d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB256v-3jUq4VGhj7M3o57E4OGmgh3sMRY',
    appId: '1:510416218437:android:0b8b9ced621a39cce5762c',
    messagingSenderId: '510416218437',
    projectId: 'gymapp-eff8d',
    storageBucket: 'gymapp-eff8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpBzhbmQ2oBDr-rkWGXWsKsCGbM-O6240',
    appId: '1:510416218437:ios:8614b1bd14f7f68de5762c',
    messagingSenderId: '510416218437',
    projectId: 'gymapp-eff8d',
    storageBucket: 'gymapp-eff8d.appspot.com',
    iosClientId: '510416218437-0r6l2dmmub0sumkhlgkogi0e0viha3pp.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpBzhbmQ2oBDr-rkWGXWsKsCGbM-O6240',
    appId: '1:510416218437:ios:8614b1bd14f7f68de5762c',
    messagingSenderId: '510416218437',
    projectId: 'gymapp-eff8d',
    storageBucket: 'gymapp-eff8d.appspot.com',
    iosClientId: '510416218437-0r6l2dmmub0sumkhlgkogi0e0viha3pp.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymbook',
  );
}
